modLoader="javafml"
loaderVersion="[4,)"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_author}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[21.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="naturescompass"
    type="optional"
    versionRange="*"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="explorerscompass"
    type="optional"
    versionRange="*"
    ordering="NONE"
    side="BOTH"

[[mixins]]
config="${mod_id}-neoforge.mixins.json"

# Access Transformer
[[accessTransformers]]
file="META-INF/accesstransformer.cfg"